#!/usr/bin/env bash
# =============================================================================
# setup-vm.sh — One-shot provisioner for a fresh Ubuntu 22.04 VM
#
# Run this ONCE on a brand-new GCP / DigitalOcean / AWS VM:
#   curl -fsSL https://raw.githubusercontent.com/YOUR_USERNAME/multiplayer-tictactoe/main/scripts/setup-vm.sh | bash
#
# Or copy it to the VM and run:
#   chmod +x setup-vm.sh && ./setup-vm.sh
#
# What it does:
#   1. Updates the OS
#   2. Installs Docker + Docker Compose plugin
#   3. Clones the repository
#   4. Prompts for production secrets
#   5. Creates .env files
#   6. Starts the full stack (docker compose up -d)
#   7. Prints the public URL
# =============================================================================

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/YOUR_USERNAME/multiplayer-tictactoe.git}"
APP_DIR="${APP_DIR:-$HOME/multiplayer-tictactoe}"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Step 1: OS update ─────────────────────────────────────────────────────────
info "Updating system packages..."

# Suppress the "Daemons using outdated libraries" ncurses dialog that appears
# during apt-get on Ubuntu 22.04 when needrestart is installed.
sudo mkdir -p /etc/needrestart/conf.d
echo "\$nrconf{restart} = 'a';" | sudo tee /etc/needrestart/conf.d/autorestart.conf > /dev/null

export DEBIAN_FRONTEND=noninteractive
sudo -E apt-get update -qq
sudo -E apt-get upgrade -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
sudo -E apt-get install -y -qq git curl ca-certificates gnupg lsb-release

# ── Step 2: Install Docker ────────────────────────────────────────────────────
if command -v docker &>/dev/null; then
  info "Docker already installed: $(docker --version)"
else
  info "Installing Docker..."
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo -E apt-get update -qq
  sudo -E apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  sudo usermod -aG docker "$USER"
  info "Docker installed: $(sudo docker --version)"
fi

DOCKER_CMD="sudo docker"
COMPOSE_CMD="sudo docker compose"

# ── Step 3: Clone repository ──────────────────────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
  info "Repository already exists at $APP_DIR — pulling latest..."
  cd "$APP_DIR" && git pull
else
  info "Cloning repository..."
  git clone "$REPO_URL" "$APP_DIR"
  cd "$APP_DIR"
fi

# ── Step 4: Production secrets ────────────────────────────────────────────────
info "Configuring production secrets..."

if [ -f "$APP_DIR/.env" ]; then
  warn ".env already exists — skipping secret generation. Edit $APP_DIR/.env manually if needed."
else
  # Auto-generate strong secrets unconditionally.
  # Interactive `read` prompts are intentionally omitted here because this
  # script is typically run via `curl | bash` (piped stdin), which means
  # `read` would consume lines from the script itself rather than keyboard input.
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  NAKAMA_SERVER_KEY=$(openssl rand -hex 16)

  # Write root .env (used by docker-compose.yml)
  cat > "$APP_DIR/.env" <<ENVEOF
# Production secrets — generated by setup-vm.sh
# DO NOT commit this file.
POSTGRES_DB=nakama
POSTGRES_USER=nakama
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NAKAMA_SERVER_KEY=${NAKAMA_SERVER_KEY}
ENVEOF

  # Write nakama/.env (used by nakama/docker-compose.yml for dev)
  cp "$APP_DIR/.env" "$APP_DIR/nakama/.env"

  info "Secrets written to $APP_DIR/.env and $APP_DIR/nakama/.env"
  echo ""
  warn "Save these values somewhere safe — they are not stored anywhere else:"
  echo "  POSTGRES_PASSWORD = $POSTGRES_PASSWORD"
  echo "  NAKAMA_SERVER_KEY = $NAKAMA_SERVER_KEY"
  echo ""
fi

# ── Step 5: Build and start the stack ────────────────────────────────────────
info "Building and starting the full stack..."
cd "$APP_DIR"
$COMPOSE_CMD up --build -d

# ── Step 6: Wait for health ───────────────────────────────────────────────────
info "Waiting for containers to become healthy (up to 90s)..."
TIMEOUT=90
ELAPSED=0
while [ $ELAPSED -lt $TIMEOUT ]; do
  NAKAMA_STATUS=$($DOCKER_CMD inspect tictactoe-nakama --format='{{.State.Health.Status}}' 2>/dev/null || echo "starting")
  if [ "$NAKAMA_STATUS" = "healthy" ]; then
    break
  fi
  echo -n "."
  sleep 5
  ELAPSED=$((ELAPSED + 5))
done
echo ""

if [ "$NAKAMA_STATUS" != "healthy" ]; then
  warn "Nakama health check did not pass within ${TIMEOUT}s."
  warn "Check logs: sudo docker logs tictactoe-nakama"
else
  info "All containers are healthy."
fi

# ── Step 7: Print status ──────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo " DEPLOYMENT COMPLETE"
echo "============================================================"
$DOCKER_CMD ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo ""

PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || echo "<VM_PUBLIC_IP>")
echo -e "  Game URL:           ${GREEN}http://${PUBLIC_IP}${NC}"
echo -e "  Nakama API:         ${GREEN}http://${PUBLIC_IP}/v2/${NC}"
echo ""
echo "  To view logs:       sudo docker compose logs -f"
echo "  To stop:            sudo docker compose down"
echo "  To update & redeploy: ./scripts/update.sh"
echo "============================================================"
